/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorDirectorios;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author paul_
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ControladorDirectorios controladorDirectorios;
    
    /**
     * Creates new form VistaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        controladorDirectorios = new ControladorDirectorios();
        
    }

    public void llenarLista(List<String> directorios){
        DefaultListModel modelo = new DefaultListModel();
        modelo.clear();
        
        for(String nombre : directorios){
            modelo.addElement(nombre);
        }
        lista.setModel(modelo);
    }
    
    public void limpiarLista(){
        DefaultListModel modelo = new DefaultListModel();
        modelo.clear();
        lista.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        lblRuta = new javax.swing.JLabel();
        txtRuta = new javax.swing.JTextField();
        btnListarDirectorios = new javax.swing.JButton();
        btnListarArchivosOcultos = new javax.swing.JButton();
        btnListarDirectoriosOcultos = new javax.swing.JButton();
        btnMostrarInformacion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        btnGestionar = new javax.swing.JMenu();
        btnCrear = new javax.swing.JMenuItem();
        btnRenombrar = new javax.swing.JMenuItem();
        btnEliminar = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTIONAR DIRECTORIOS");

        lblRuta.setBackground(new java.awt.Color(204, 255, 255));
        lblRuta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRuta.setText("RUTA:");
        desktopPane.add(lblRuta);
        lblRuta.setBounds(210, 60, 40, 20);
        desktopPane.add(txtRuta);
        txtRuta.setBounds(250, 60, 260, 30);

        btnListarDirectorios.setBackground(new java.awt.Color(204, 255, 255));
        btnListarDirectorios.setText("Listar Directorios");
        btnListarDirectorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDirectoriosActionPerformed(evt);
            }
        });
        desktopPane.add(btnListarDirectorios);
        btnListarDirectorios.setBounds(70, 110, 140, 30);

        btnListarArchivosOcultos.setBackground(new java.awt.Color(204, 255, 255));
        btnListarArchivosOcultos.setText("Listar Archivos Ocultos");
        btnListarArchivosOcultos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarArchivosOcultosActionPerformed(evt);
            }
        });
        desktopPane.add(btnListarArchivosOcultos);
        btnListarArchivosOcultos.setBounds(220, 110, 170, 30);

        btnListarDirectoriosOcultos.setBackground(new java.awt.Color(204, 255, 255));
        btnListarDirectoriosOcultos.setText("Listar Directorios Ocultos");
        btnListarDirectoriosOcultos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDirectoriosOcultosActionPerformed(evt);
            }
        });
        desktopPane.add(btnListarDirectoriosOcultos);
        btnListarDirectoriosOcultos.setBounds(400, 110, 180, 30);

        btnMostrarInformacion.setBackground(new java.awt.Color(204, 255, 255));
        btnMostrarInformacion.setText("Mostrar informacion");
        btnMostrarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarInformacionActionPerformed(evt);
            }
        });
        desktopPane.add(btnMostrarInformacion);
        btnMostrarInformacion.setBounds(100, 330, 180, 30);

        jScrollPane1.setViewportView(lista);

        desktopPane.add(jScrollPane1);
        jScrollPane1.setBounds(70, 160, 240, 160);

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane2.setViewportView(txtArea);

        desktopPane.add(jScrollPane2);
        jScrollPane2.setBounds(330, 160, 240, 160);

        btnGestionar.setMnemonic('f');
        btnGestionar.setText("Gestionar Directorios");

        btnCrear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        btnCrear.setMnemonic('o');
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        btnGestionar.add(btnCrear);

        btnRenombrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        btnRenombrar.setMnemonic('s');
        btnRenombrar.setText("Renombrar");
        btnRenombrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenombrarActionPerformed(evt);
            }
        });
        btnGestionar.add(btnRenombrar);

        btnEliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        btnEliminar.setMnemonic('a');
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        btnGestionar.add(btnEliminar);

        btnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        btnSalir.setMnemonic('x');
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnGestionar.add(btnSalir);

        menuBar.add(btnGestionar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnRenombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenombrarActionPerformed
        
        
    }//GEN-LAST:event_btnRenombrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnListarDirectoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDirectoriosActionPerformed
        String ruta = txtRuta.getText();
        if(ruta==null){
            JOptionPane.showMessageDialog(this, "El campo de la ruta debe ser llenado");
            
        }else{
            if(controladorDirectorios.validarRuta(ruta)){
                List<String> directorios = controladorDirectorios.listarDirectorios(ruta);
                if(directorios.isEmpty()){
                    JOptionPane.showMessageDialog(this, "El directorio esta vacio");
                    limpiarLista();
                    
                }else{
                    llenarLista(directorios);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Ruta del directorio incorrecta");
            }
        }
        
    }//GEN-LAST:event_btnListarDirectoriosActionPerformed

    private void btnListarArchivosOcultosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarArchivosOcultosActionPerformed
        String ruta = txtRuta.getText();
        if(ruta==null){
            JOptionPane.showMessageDialog(this, "El campo de la ruta debe ser llenado");
            
        }else{
            if(controladorDirectorios.validarRuta(ruta)){
                List<String> directorios = controladorDirectorios.listarArchivosOcultos(ruta);
                if(directorios.isEmpty()){
                    JOptionPane.showMessageDialog(this, "No hay archivos ocultos");
                    limpiarLista();
                    
                }else{
                    llenarLista(directorios);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Ruta del directorio incorrecta");
            }
        }
        
    }//GEN-LAST:event_btnListarArchivosOcultosActionPerformed

    private void btnListarDirectoriosOcultosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDirectoriosOcultosActionPerformed
        String ruta = txtRuta.getText();
        if(ruta==null){
            JOptionPane.showMessageDialog(this, "El campo de la ruta debe ser llenado");
            
        }else{
            if(controladorDirectorios.validarRuta(ruta)){
                List<String> directorios = controladorDirectorios.listarDirectoriosOcultos(ruta);
                if(directorios.isEmpty()){
                    JOptionPane.showMessageDialog(this, "El directorio oculto esta vacio");
                    limpiarLista();
                    
                }else{
                    llenarLista(directorios);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Ruta del directorio incorrecta");
            }
        }
        
    }//GEN-LAST:event_btnListarDirectoriosOcultosActionPerformed

    private void btnMostrarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarInformacionActionPerformed
        
        
    }//GEN-LAST:event_btnMostrarInformacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCrear;
    private javax.swing.JMenuItem btnEliminar;
    private javax.swing.JMenu btnGestionar;
    private javax.swing.JButton btnListarArchivosOcultos;
    private javax.swing.JButton btnListarDirectorios;
    private javax.swing.JButton btnListarDirectoriosOcultos;
    private javax.swing.JButton btnMostrarInformacion;
    private javax.swing.JMenuItem btnRenombrar;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JList<String> lista;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables

}
